// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CH.Spartan.Maps;

namespace CH.Spartan.Maps
{

    public class AddressComponent
    {

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("province")]
        public string Province { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("citycode")]
        public string Citycode { get; set; }

        [JsonProperty("district")]
        public string District { get; set; }

        [JsonProperty("adcode")]
        public string Adcode { get; set; }

        [JsonProperty("township")]
        public string Township { get; set; }

        [JsonProperty("towncode")]
        public string Towncode { get; set; }

        [JsonProperty("neighborhood")]
        public Neighborhood Neighborhood { get; set; }

        [JsonProperty("building")]
        public Building Building { get; set; }

        [JsonProperty("streetNumber")]
        public StreetNumber StreetNumber { get; set; }

        [JsonProperty("businessAreas")]
        public BusinessArea[] BusinessAreas { get; set; }
    }

}
