// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CH.Spartan.Maps;

namespace CH.Spartan.Maps
{

    public class Regeocode
    {

        [JsonProperty("formatted_address")]
        public string FormattedAddress { get; set; }

        [JsonProperty("addressComponent")]
        public AddressComponent AddressComponent { get; set; }

        [JsonProperty("pois")]
        public Pois[] Pois { get; set; }

        [JsonProperty("roads")]
        public Road[] Roads { get; set; }

        [JsonProperty("roadinters")]
        public Roadinter[] Roadinters { get; set; }

        [JsonProperty("aois")]
        public object[] Aois { get; set; }
    }

}
