// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CH.Spartan.Maps;

namespace CH.Spartan.Maps
{

    public class Roadinter
    {

        [JsonProperty("direction")]
        public string Direction { get; set; }

        [JsonProperty("distance")]
        public string Distance { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("first_id")]
        public string FirstId { get; set; }

        [JsonProperty("first_name")]
        public string FirstName { get; set; }

        [JsonProperty("second_id")]
        public string SecondId { get; set; }

        [JsonProperty("second_name")]
        public string SecondName { get; set; }
    }

}
