// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CH.Spartan.Maps;

namespace CH.Spartan.Maps
{

    public class StreetNumber
    {

        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("direction")]
        public string Direction { get; set; }

        [JsonProperty("distance")]
        public string Distance { get; set; }
    }

}
